version: "0.1"
services:
  web:
    image: local:latest
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 1000M
      restart_policy:
        condition: on-failure
    ports:
      - "10000:10000"
    networks:
      - webnet
networks:
  webnet:
