version: '2.2'
services:
  backend-service:  
    image: backend-service:latest
    container_name: backend-service
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /bin/netstat:/bin/netstat
      - ./seeds/config/default_config.toml:/opt/seeds/config/default_config.toml 
    ports:
      - 9999:9999
    links:
      - cache-service
      - storage-service
  storage-service:
    image: storage:latest
    container_name: storage-service
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /data/1:/data/db
      - /data/2:/data/configdb 
    ports:
      - 27017:27017
  cache-service:
    image: cache:latest
    container_name: cache-service
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /usr/bin:/usr/bin/
    ports:
      - 6379:6379
